[project]
name = "rag-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.4.1",
    "fastapi>=0.128.0",
    "ollama>=0.6.1",
    "pydantic>=2.12.5",
    "uvicorn>=0.40.0",
]
